corner-radius = 9;
round-borders = 9;
# backend = "xrender";
backend = "glx";
vsync = true;

blur-background = true;
blur-background-frame = true;
blur-method = "dual_kawase";
blur-strength = 0;
blur-size = 12;
blur-background-fixed = true;
glx-no-stencil = true;
glx-copy-from-front = false;
# inactive-dim = 0.1;
detect-client-opacity = true;
detect-rounded-corners = true;
inactive-opacity-override = true;

