# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=false
separator_block_width=0
border_top=2
border_left=1
border_right=2
border_bottom=2



[window_title]
command=~/.config/i3blocks/scripts/title3.sh
interval=persist
min_width=1160
align=center
separator=false
markup=pango
background=#7193ad
separator_block_width=87


[brightness]
command=~/.config/i3blocks/scripts/brightness_display.sh
interval=once
signal=3
min_width=8
markup=pango
align=center
color=#ff5555
background=#282737
label=<span background='#ff5555' foreground='#030303'>  </span>
# border=#ff5555




# Memory
[memory]
command=echo "<span weight='bold' style='italic'>$(free -h | awk '/^Mem:/ {print " " $3 "/" $2}')</span> "
interval=10
color=#e1aae3
label=<span background='#b95cbd' foreground='#030303' weight="bold"> MEM </span>
align=center
min_width=80
markup=pango
# border=#b95cbd

# CPU usage
[cpu_usage]
command=echo "<span weight='bold' style='italic'> $(top -bn1 | grep 'Cpu(s)' | sed 's/.*, *\([0-9.]*\)%* id.*/\1/' | awk '{printf "%3.1f%%", 100-$1}') </span>"
interval=5
color=#ABE9B3
background=#282737
label=<span background='#ABE9B3' foreground='#030303' weight="bold"> CPU </span>
min_width=50
align=center
markup=pango
# border=#ABE9B3


[time]
command=echo "<span weight='bold' style='italic'> $(date '+%I:%M %p') </span>"
interval=60
color=#96CDFB
background=#282737
label=<span background='#96CDFB' foreground='#030303' weight="bold"> 󱑆 </span>
markup=pango
# border=#96CDFB

[battery]
command=~/.config/i3blocks/scripts/battery.sh
interval=30
markup=pango
min_width=25

